/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as SSlugManageRouteImport } from './routes/s.$slug.manage'
import { Route as SSlugCheckoutRouteImport } from './routes/s.$slug.checkout'
import { Route as SSlugCartRouteImport } from './routes/s.$slug.cart'
import { Route as SSlugProductIdRouteImport } from './routes/s.$slug.product.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const SSlugManageRoute = SSlugManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCheckoutRoute = SSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCartRoute = SSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugProductIdRoute = SSlugProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/zones': typeof AdminZonesRoute
  '/product/$id': typeof ProductIdRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/manage': typeof SSlugManageRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/zones': typeof AdminZonesRoute
  '/product/$id': typeof ProductIdRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/manage': typeof SSlugManageRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/zones': typeof AdminZonesRoute
  '/product/$id': typeof ProductIdRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/manage': typeof SSlugManageRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/stores'
    | '/admin/zones'
    | '/product/$id'
    | '/s/$slug'
    | '/admin/'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/manage'
    | '/s/$slug/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/stores'
    | '/admin/zones'
    | '/product/$id'
    | '/s/$slug'
    | '/admin'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/manage'
    | '/s/$slug/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/stores'
    | '/admin/zones'
    | '/product/$id'
    | '/s/$slug'
    | '/admin/'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/manage'
    | '/s/$slug/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProductIdRoute: typeof ProductIdRoute
  SSlugRoute: typeof SSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$slug/manage': {
      id: '/s/$slug/manage'
      path: '/manage'
      fullPath: '/s/$slug/manage'
      preLoaderRoute: typeof SSlugManageRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/checkout': {
      id: '/s/$slug/checkout'
      path: '/checkout'
      fullPath: '/s/$slug/checkout'
      preLoaderRoute: typeof SSlugCheckoutRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/cart': {
      id: '/s/$slug/cart'
      path: '/cart'
      fullPath: '/s/$slug/cart'
      preLoaderRoute: typeof SSlugCartRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/product/$id': {
      id: '/s/$slug/product/$id'
      path: '/product/$id'
      fullPath: '/s/$slug/product/$id'
      preLoaderRoute: typeof SSlugProductIdRouteImport
      parentRoute: typeof SSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SSlugRouteChildren {
  SSlugCartRoute: typeof SSlugCartRoute
  SSlugCheckoutRoute: typeof SSlugCheckoutRoute
  SSlugManageRoute: typeof SSlugManageRoute
  SSlugProductIdRoute: typeof SSlugProductIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugCartRoute: SSlugCartRoute,
  SSlugCheckoutRoute: SSlugCheckoutRoute,
  SSlugManageRoute: SSlugManageRoute,
  SSlugProductIdRoute: SSlugProductIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProductIdRoute: ProductIdRoute,
  SSlugRoute: SSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
